### ISSUE TITLE
enable delete-selection-mode

### ISSUE THREAD

**Issue by ijp** [technomancy/better-defaults#12]
Adding this so I don't forget.

I think this is a good addition, since it's the way basically every other program under the sun works, but on the other hand, since when has emacs been like every other program under the sun?

I need some more "data" before I would feel comfortable committing this.

**Comment by kevinjamescasey** [comment]
I'd love to hear from somebody that wants delete-selection-mode turned off. I can't think of a situation where you would select a region only to do nothing with the selected region.

**Comment by technomancy** [comment]
Not all region commands deactivate the region when you're done. For
instance, sometimes I will mark a number of successive forms, evaluate
the region, and then continue editing. Having the forms I just evaluated
deleted just because I started typing would be very annoying.

**Comment by kevinjamescasey** [comment]
I was afraid of that, but the few simple things I tried did deactivate the region...

I guess its a choice between C-g in scenarios like yours and C-d when you want to overwrite -- can't have it both ways.

> Whenever the mark is active, you can deactivate it by typing C-g (see Quitting). Most commands that operate on the region also automatically deactivate the mark, like C-x C-u in the above example.

Maybe there is a way to make all commands invoked with an active mark deactivate the mark. Otherwise each command like eval-region would have to set the deactivate-mark variable.

> Variable: deactivate-mark
> If an editor command sets this variable non-nil, then the editor command loop deactivates the mark after the command returns (if Transient Mark mode is enabled). All the primitives that change the buffer set deactivate-mark, to deactivate the mark when the command is finished.

I guess people may want to do multiple non-buffer-changing commands on the same region in sequence, like eval it a half dozen times for side effects. ¯\_(ツ)_/¯

**Comment by technomancy** [comment]
I agree it might make sense to have all region-affecting commands deactivate the mark for consistency, but since that's not currently the case this is problematic.
