### ISSUE TITLE
save-place behavior has changed.

### ISSUE THREAD

**Issue by jaccarmac** [technomancy/better-defaults#15]
The online documentation in Emacs for this change is sorely lacking, but AFAIK the following changed:
1. `save-place` no longer does anything.
2. A new variable `save-place-mode` has been created which appears to mirror the old `save-place`.
3. A new mode `save-place-mode` has been created which seems to affect the variable `save-place-mode` somehow.

`save-place-file` works the same way.

An Emacs started with `-Q` has the variables from points 1 and 2 above set to `nil`, while an Emacs with better-defaults installed has both set to `t`. The latter Emacs also appears to have the mode `save-place-mode` loaded, but `save-place-alist` is not populated until the mode is toggled on and off or a snippet a la jaccarmac/dot-emacs-dot-d@215c295566d3bfa883fb0d10c81c968d99e2756a is added to the init file.

The above snippet is the lazy easy solution, taken from [this Emacs Stack Exchange answer](http://emacs.stackexchange.com/a/12712). [This answer](http://emacs.stackexchange.com/a/14675) is slightly more complex and perhaps compatible with the old `save-place`, but I have not tried it.

**Comment by gonewest818** [comment]
Just a comment that pull request #36 removes the "better" default for `save-place-file` because the actual default (since Emacs 24.4) already puts the file in `user-emacs-directory`.   In addition, because `save-place-mode` was introduced in Emacs 25.1 and is used in this package, the same PR #36 makes Emacs 25.1 an explicit requirement for this package.

**Comment by technomancy** [comment]
Cool; I think we're set here then.
