### ISSUE TITLE
Initialize function

### ISSUE THREAD

**Issue by Profpatsch** [technomancy/better-defaults#3]
The module is activated whenever it is installed. This violates point one of the Coding Guidelines:
https://www.gnu.org/software/emacs/manual/html_node/elisp/Coding-Conventions.html#Coding-Conventions

**Comment by technomancy** [comment]
Is there any use case for having this package installed but not using it? I can't think of one.

**Comment by Profpatsch** [comment]
Whoa, that’s old.

Well, it’s against emacs code guidelines.

**Comment by mzuther** [comment]
I'm with Profpatsch that it's *always* a good idea to follow code guidelines, even if you yourself can't see why you should. There are reason for these guidelines, if only to ensure a consistent user experience.

That being said, my work computer currently *poses* a use case. I'm using Emacs 25.1.1 on Windows 7 with the command `bin\runemacs.exe --fullheight`, and because of one of the commands in `better-defaults`, Emacs doesn't start up maximised any more.

I certainly don't blame `better-defaults`for this behaviour. But with `(require 'better-defaults)`, I could try to move the package's initialisation to a place where it didn't break the maximisation code. Now, I'm stuck with a binary choice: either maximise the window myself each time I start Emacs or delete `better-defaults` from my system.

**Comment by raxod502** [comment]
I'd like to put in a vote for `(require 'better-defaults)` instead of using an autoload, due to a rather unfortunate feature of package.el: it activates the autoloads of all installed packages, even if they're not referenced anywhere in one's init-file. Many people have a list of packages defined in their init-file, with instructions that tell package.el to install any that are missing. But the persistent-install behavior means that if better-defaults is *removed* from that list, then its autoloads will continue to be activated, even though the package is not referenced anywhere in the init-file. This is very confusing, and breaks reproducibility! It's also one of the reasons that avoiding destructive behavior (e.g. changing settings) in autoloads is generally recommended to be avoided.

**Comment by Profpatsch** [comment]
This issue keeps getting necromanced.

**Comment by Trevoke** [comment]
Now that I have a bunch of years of using emacs behind me, I agree with `(require 'better-defaults)` as a suggestion.

**Comment by raxod502** [comment]
I don't use better-defaults, but as I think it's important for newcomers to the Emacs ecosystem to start off with best practices, I've made a simple pull request to fix this issue.

**Comment by mzuther** [comment]
Thank you very much for reconsidering! :)
